export const primary1 = '#733FFF'; //보라
export const primary2 = '#8C31CB';
export const secondary1 = '#431AB2';
export const secondary2 = '#E3D9FF';
export const error = '#FF3333';
export const call = '#32FF8C';
export const onColorBackground = '#FFFFFF';
export const border = '#EEEEEE';
export const defaultColor = '#CCCCCC';
export const itemTitle = '#555555';
export const textBlack = '#111111';
export const black = '#000000';
export const vaildRed = '#ff3333';
export const modalBackCover = '#111111CC';
